export const ALL_PRODCUTS_REQUEST = 'ALL_PRODCUTS_REQUEST'
export const ALL_PRODCUTS_SUCCESS = 'ALL_PRODCUTS_SUCCESS'
export const ALL_PRODCUTS_FAIL = 'ALL_PRODCUTS_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS"